#farma:
#  app:
#    jwtExpiration: 86400
#    jwtSecret: jwtOKRboardSecretKey


spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/okrboard
    username: root
    password: root
  #    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
  server:
      port: 8080
#spring:
#  jpa:
#    database: MYSQL
#    hibernate:
#      ddl-auto: update
#    show-sql: 'false'
#    properties.hibernate.temp.use_jdbc_metadata_defaults: false
#  profiles:
#    active:
#    - prod
#
spring.jackson.serialization.fail-on-empty-beans: false